amicodingparina/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import InputResource
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

input_resource = InputResource()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('khoj.urls')),
    path('api/v1/', include(input_resource.urls)),
]

urlpatterns += staticfiles_urlpatterns()
handler404 = 'khoj.views.page_not_found_view'

khoj/urls.py
from django.urls import path
from . import views

app_name = 'khoj'

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('', views.home, name="home"),
    path('search/', views.search_view, name="search_view"),
    path('generate_api_key/', views.generate_api_key, name='generate_api_key')
]

api/models.py
from tastypie.resources import ModelResource
from tastypie.authorization import Authorization
from tastypie.authentication import ApiKeyAuthentication
from tastypie.exceptions import BadRequest
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

from khoj.models import Input


class InputResource(ModelResource):
    class Meta:
        queryset = Input.objects.all()
        resource_name = 'items'
        authorization = Authorization()
        authentication = ApiKeyAuthentication()
        always_return_data = True
        allowed_methods = ['get']

    def obj_get_list(self, bundle):
        # Get the parameters
        start_datetime = bundle.request.GET.get('start_datetime', None)
        end_datetime = bundle.request.GET.get('end_datetime', None)
        user_id = bundle.request.GET.get('user_id', None)

        # If all the parameters are provided, filter the results
        if start_datetime and end_datetime and user_id:
            try:
                user = User.objects.get(id=user_id)
            except ObjectDoesNotExist:
                raise BadRequest("No user found with id: {0}".format(user_id))

            results = Input.objects.filter(
                user=user, timestamp__gte=start_datetime, timestamp__lte=end_datetime)

        # Else, return all results
        else:
            results = Input.objects.all()

        return results

khoj/models.py
from django.db import models
from .forms import User


class Input(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    input_values = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

khoj/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


def validate_comma_separated_integer_list(value):
    values = value.split(',')
    for val in values:
        try:
            int(val)
        except ValueError:
            # raise exception if value is not an integer
            raise forms.ValidationError(f"{val} is not an integer")


class InputForm(forms.Form):
    input_values = forms.CharField(
        validators=[validate_comma_separated_integer_list])
    search_value = forms.IntegerField()

api/views.py
from django.shortcuts import render

# Create your views here.

khoj/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from tastypie.models import ApiKey

from .models import *
from .forms import *


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('khoj:latest')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)

                return redirect('khoj:login')

        context = {'form': form}
        return render(request, 'khoj/register.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('khoj:search_view')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('khoj:search_view')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'khoj/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('khoj:login')


def home(request):
    context = {}
    return render(request, 'khoj/home.html', context)


@login_required(login_url='khoj:login')
def search_view(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            # Get the input values
            input_values = map(
                int, form.cleaned_data['input_values'].split(','))

            # Sort the input values in descending order
            sorted_input_values = sorted(input_values, reverse=True)

            # Convert the sorted input values to a string [Unpacking array]
            sorted_input_values_str = ', '.join(
                str(num) for num in sorted_input_values)

            # Create an instance of Input with sorted input values
            input_instance = Input(
                input_values=sorted_input_values_str, user=request.user)
            input_instance.save()

            # Check if the search value is in the sorted input values
            # Ensure you have a 'search_value' field in your form
            search_value = form.cleaned_data['search_value']
            if search_value in sorted_input_values:
                result = True
            else:
                result = False

            return render(request, 'khoj/search.html', {'form': form, 'result': result})
    else:
        form = InputForm()
    return render(request, 'khoj/search.html', {'form': form})


@login_required
def generate_api_key(request):
    api_key, created = ApiKey.objects.get_or_create(user=request.user)
    if created:
        generated_key = api_key.key
    else:
        generated_key = api_key.key

    return render(request, 'khoj/generate_api_key.html', {'generated_key': generated_key})


def page_not_found_view(request, exception):
    return render(request, "khoj/404.html", {})

khoj/templates/khoj/generate_api_key.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Static Files -->
	<link rel="stylesheet" type="text/css" href="{% static '/khoj/css/register.css' %}">
	<link rel="shortcut icon" type="icon" href="{% static '/khoj/favicon.ico' %}">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
		integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
		
	<!-- Google Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;700&display=swap" rel="stylesheet">

	<!-- Favicon -->
	<link rel="shortcut icon" type="icon" href="{% static '/favicon.ico' %}">

	<title>খোঁজ দ্যা সার্চ । আমি কোডিং পারি না</title>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background-image: url("https://images.unsplash.com/photo-1581472723648-909f4851d4ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80");
			background-size: cover;
      		background-position: center;
			font-family: 'Hind Siliguri', sans-serif;
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: transparent;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
			backdrop-filter: blur(5px);
		}

		input {
			background-color: transparent!important;
			color: #fff!important;
			border: 2px solid #fff!important;
		}

		input::placeholder {
			color: #fff!important;
		}

		.form_container {
			margin-top: 20px;
		}

		#form-title {
			color: #fff;

		}

		a {
			text-decoration: none;
			color: #fff;
		}

		.login_btn {
			width: 100%;
			background: transparent !important;
			color: white !important;
			border: 2px solid #fff;
			border-radius: 1rem;
		}

		.login_btn:hover {
			width: 100%;
			background: #fff !important;
			color: #000 !important;
			border: 2px solid #fff;
		}

		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.login_container {
			padding: 0 2rem;
		}

		.input-group-text {
			background: transparent !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages {
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card w-50">
				<div class="text-center m-5 d-flex justify-content-between">
					<a href="{% url 'khoj:home' %}"><i class="fas fa-arrow-left"></i>Home</a>
					<a href="{% url 'khoj:search_view' %}">Search<i class="fas fa-arrow-right"></i></a>
				</div>
				<div class="d-flex justify-content-center">
					<h3 class="text-white">Generated API Key for {{ request.user }}</h3>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links text-white">
						<h4 class="bg-secondary rounded-pill p-2">{{ generated_key }}</h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		// Adding placeholder to form fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder = 'Input Values..';
		form_fields[2].placeholder = 'Search Value..';

		for (var field in form_fields) {
			form_fields[field].className += ' form-control'
		}
	</script>
</body>

</html>

khoj/templates/khoj/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Google Font -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;700&display=swap" rel="stylesheet">

  <!-- Favicon -->
  <link rel="shortcut icon" type="icon" href="{% static '/favicon.ico' %}">

  <title>Home । আমি কোডিং পারি না</title>

  <style>
    body, html {
      height: 100%;
      margin: 0;
      padding: 0;
      font-family: 'Hind Siliguri', sans-serif;
    }

    .landing-page {
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      color: #fff;
      text-align: center;
      background-size: cover;
      background-position: center;
      background-image: url("https://images.unsplash.com/photo-1581472723648-909f4851d4ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80");
    }

    input::placeholder {
        color: #fff!important;
    }

    input {
        background-color: transparent!important;
        color: #fff!important;
        border: 2px solid #fff!important;
    }


    .landing-text {
      font-size: 3.5rem;
      font-weight: bold;
      margin-bottom: 20px;
    }

    a {
        text-decoration: none;
        color: #fff;
    }

    .login-button {
      font-size: 1.2rem;
      padding: 10px 20px;
      border: none;
      border-radius: 1rem;
      background-color: transparent;
      border: 2px solid #fff;
      color: #eee;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .login-button:hover {
      background-color: #fff;
      color: #000;
    }
  </style>

</head>

<body>
    <div class="landing-page" id="landingPage">
        <div class="landing-text">আপনি কি কোডিং পারেন না!</div>
        <p>তাহলে দেরি কেন? কোডিং শিখতে লগিন করুন এখনি</p>
        <div class="landing-text">👇</div>
        {% if user.is_authenticated %}              
            <a class="login-button" href="{% url 'khoj:logout' %}">Logout(<strong>{{request.user}}</strong>)</a>
            <h3>Or</h3>
            <a href="{% url 'khoj:generate_api_key' %}"><h3>Generate API Key</h3><i class="fas fa-arrow-right"></i></a>
        {% else %}
            <a class="login-button" href="{% url 'khoj:login' %}">Login</a>
        {% endif %}
    </div>

</body>

</html>

khoj/templates/khoj/login.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
	integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
	integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

	<!-- Favicon -->
	<link rel="shortcut icon" type="icon" href="{% static '/favicon.ico' %}">
	
	<title>Login । আমি কোডিং পারি না</title>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background-image: url("https://images.unsplash.com/photo-1581472723648-909f4851d4ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80");
			background-size: cover;
      		background-position: center;
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: transparent;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
			backdrop-filter: blur(5px);
		}

		input::placeholder {
			color: #fff!important;
		}

		input {
			background-color: transparent!important;
			color: #fff!important;
			border: 2px solid #fff!important;
		}

		.form_container {
			margin-top: 20px;
		}

		#form-title {
			color: #fff;

		}

		a {
			text-decoration: none;
			color: #fff;
		}

		.login_btn {
			width: 100%;
			background: transparent !important;
			color: white !important;
			border: 2px solid #fff;
			border-radius: 1rem;
		}

		.login_btn:hover {
			width: 100%;
			background: #fff !important;
			color: #000 !important;
			border: 2px solid #fff;
		}

		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.login_container {
			padding: 0 2rem;
		}

		.input-group-text {
			background: transparent !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages {
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="text-center m-5 d-flex justify-content-between">
					<a href="{% url 'khoj:home' %}"><i class="fas fa-arrow-left"></i>Home</a>
				</div>
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

							<input type="password" name="password" placeholder="Password..." class="form-control">
						</div>

						<div class="d-flex justify-content-center mt-3 login_container">
							<input class="btn login_btn" type="submit" value="Login">
						</div>
					</form>

				</div>

				{% for message in messages %}
				<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links text-white">
						Don't have an account? <a href="{% url 'khoj:register' %}" class="ml"> Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

khoj/templates/khoj/search.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Static Files -->
	<link rel="stylesheet" type="text/css" href="{% static '/khoj/css/register.css' %}">
	<link rel="shortcut icon" type="icon" href="{% static '/khoj/favicon.ico' %}">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
		integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
		
	<!-- Google Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;700&display=swap" rel="stylesheet">

	<!-- Favicon -->
	<link rel="shortcut icon" type="icon" href="{% static '/favicon.ico' %}">

	<title>খোঁজ দ্যা সার্চ । আমি কোডিং পারি না</title>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background-image: url("https://images.unsplash.com/photo-1581472723648-909f4851d4ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80");
			background-size: cover;
      		background-position: center;
			font-family: 'Hind Siliguri', sans-serif;
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: transparent;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
			backdrop-filter: blur(5px);
		}

		input {
			background-color: transparent!important;
			color: #fff!important;
			border: 2px solid #fff!important;
		}

		input::placeholder {
			color: #fff!important;
		}

		.form_container {
			margin-top: 20px;
		}

		#form-title {
			color: #fff;

		}

		a {
			text-decoration: none;
			color: #fff;
		}

		.login_btn {
			width: 100%;
			background: transparent !important;
			color: white !important;
			border: 2px solid #fff;
			border-radius: 1rem;
		}

		.login_btn:hover {
			width: 100%;
			background: #fff !important;
			color: #000 !important;
			border: 2px solid #fff;
		}

		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.login_container {
			padding: 0 2rem;
		}

		.input-group-text {
			background: transparent !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages {
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="text-center m-5 d-flex justify-content-between">
					<a href="{% url 'khoj:home' %}"><i class="fas fa-arrow-left"></i>Home</a>
					<a href="{% url 'khoj:generate_api_key' %}">Generate API Key<i class="fas fa-arrow-right"></i></a>
				</div>
				<div class="d-flex justify-content-center">
					<h3 id="form-title">খোঁজ দ্যা সার্চ</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.input_values}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.search_value}}
						</div>



						<div class="d-flex justify-content-center mt-3 login_container">
							<input class="btn login_btn" type="submit" value="খোঁজ">
						</div>

					</form>
				</div>

				<div class="text-white">{{form.errors}}</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links text-white">
						<h4>Result: {{ result }}</h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		// Adding placeholder to form fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder = 'Input Values..';
		form_fields[2].placeholder = 'Search Value..';

		for (var field in form_fields) {
			form_fields[field].className += ' form-control'
		}
	</script>
</body>

</html>